apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-k8s-demo
  namespace: default
spec:
  replicas : 3
  selector:
    matchLabels :
      app: springboot-k8s-demo
  template:
    metadata:
      labels:
        app: springboot-k8s-demo
    spec:
      containers:
        - name: springboot-k8s-demo
          image: springboot-k8s-demo:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

